apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mind-eden-ns

metadata:
  name: mind-eden
  namespace: mind-eden-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/qianxue-test-mindpotential
  newTag: 1.0.10

commonLabels:
  app: mind-eden
  managed-by: argocd


